name: Notify Discord on Push

on:
  push:
    branches:
      - main 

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"username\": \"🦊 GitHub 알람봇\",
              \"avatar_url\": \"https://i.imgur.com/AfFp7pu.png\",
              \"content\": \"📢 **$GITHUB_ACTOR** 님이 [$GITHUB_REPOSITORY]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY)에 푸시했습니다.\\n브랜치: $GITHUB_REF\\n커밋: $GITHUB_SHA\"
            }" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
